# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: google/cloud-sdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool

    working_directory: /home/main
    steps:
      - checkout
      

      # specify any bash command here prefixed with `run: `
      - run: echo $CLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: mkdir src
      - run: mkdir pkg
      - run: mkdir bin
      - run: curl -O https://storage.googleapis.com/golang/go1.10.3.linux-amd64.tar.gz
      - run: tar -C /usr/local -xzf go1.10.3.linux-amd64.tar.gz  
      - run: rm go1.10.3.linux-amd64.tar.gz
      - run: apt-get update && apt-get -y --only-upgrade install google-cloud-sdk-app-engine-go 
      - run: go get cloud.google.com/go/pubsub
      - run: go get -u google.golang.org/appengine 
      - run: gcloud app deploy  
      - run: gcloud app browse
      #- run:                 
