version: 2
jobs:
  build:
    working_directory: ~/webapp
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout


      # specify any bash command here prefixed with `run: `
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: curl -OL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-203.0.0-linux-x86_64.tar.gz
      - run: sudo tar -xz -C /usr/bin -f google-cloud-sdk-203.0.0-linux-x86_64.tar.gz
     # - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
     # - run: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
     # - run: sudo /opt/google-cloud-sdk/bin/gcloud config set project cp100-204508  
      - run: mkdir src
      - run: mkdir pkg
      - run: mkdir bin
      - run: go get cloud.google.com/go/pubsub
      - run: go get google.golang.org/appengine
      #- run: 
      - run: gcloud -q app deploy app.yaml
      #- run:                
